- name: Launch MCS Card
  hosts: all
  gather_facts: no

  tasks:


    - name: Get the list of microservice containers
      uri:
         url: "http://{{ cms_url }}/cms/networkmap?v=1620732259069"
         method: POST
         headers:
           Connection: 'keep-alive'
           Authorization: 'Bearer {{ cms_token }} '
           Accept: 'application/json, text/plain, */*'
         validate_certs: no
         timeout: 420
         body: '{"context":"MICROSVC_CONTAINERCONFIG","action":"MICROSVC_CONTAINERCONFIG_GETALL","object":{"dgId":""}}'
         body_format: json
      register: container_add
      failed_when: container_add.status not in [200, 201]

    - name: Filter microservice containers list
      set_fact:
          doc1: "{{ container_add |to_json| from_json | json_query('json.data.values[]') }}"


#    - name: Container delete request
#      set_fact:
#        container_delete: >
#           {% for item in doc1 %}
#             {% if item.SERVICETYPE == SERVICETYPE and item.STATUS == 3 %}
#                 {"context":"MICROSVC_CONTAINERCONFIG","action":"MICROSVC_CONTAINERCONFIG_LAUNCH","actionObject":[
#                           {"CONTAINER_SIGCARDID":{{item.CONTAINER_SIGCARDID}},"IPADDRESS":"{{ item.IPADDRESS }}","SIGNALINGCARDTYPE":{{ item.SIGNALINGCARDTYPE }},"STATUS":3,"SIGNALINGCARD_NAME":"{{ item.SIGNALINGCARD_NAME }}","PTTSERVERID":"{{ item.PTTSERVERID }}"}], "object":{"dgId": "{{ item.PTTSERVERID[2:-1] }}"}
#                }
#             {% endif %}
#           {% endfor %}
#
#    - name: delete microservice containers
#      uri:
#        url: "http://{{ cms_url }}/cms/config?v=1760345592484"
#        method: POST
#        headers:
#          Connection: 'keep-alive'
#          Authorization: 'Bearer {{ cms_token }} '
#          Accept: 'application/json, text/plain, */*'
#        validate_certs: no
#        timeout: 420
#        body: '{{ container_delete }}'
#        body_format: json
#      register: container_delete
#      failed_when: container_launch.json.code | int not in [200, 201]
